export enum TRANSACTION_STATUS {
  CREATED = 'CREATED',
  APPROVED = 'APPROVED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  VOIDED = 'VOIDED',
}

export enum PAYMENT_METHOD {
  PAYPAL = 'Paypal',
}
